namespace Knock
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// Filters selecting which messages in a channel to bulk update
    /// </summary>
    public class BulkUpdateChannelMessagesOptions : BaseOptions
    {
        /// <summary>
        /// Whether to `exclude`, `include` or `only` include archived messages
        /// </summary>
        [JsonProperty("archived")]
        public string Archived { get; set; }

        /// <summary>
        /// Limits to messages with the given delivery status
        /// </summary>
        [JsonProperty("delivery_status")]
        public string DeliveryStatus { get; set; }

        /// <summary>
        /// Limits to messages with the given engagement status
        /// </summary>
        [JsonProperty("engagement_status")]
        public string EngagementStatus { get; set; }

        /// <summary>
        /// Limits to messages that have (or don't have) a tenant
        /// </summary>
        [JsonProperty("has_tenant")]
        public bool? HasTenant { get; set; }

        /// <summary>
        /// Limits to messages newer than the given ISO8601 datetime
        /// </summary>
        [JsonProperty("newer_than")]
        public string NewerThan { get; set; }

        /// <summary>
        /// Limits to messages older than the given ISO8601 datetime
        /// </summary>
        [JsonProperty("older_than")]
        public string OlderThan { get; set; }

        /// <summary>
        /// Limits to messages for the given recipient ids
        /// </summary>
        [JsonProperty("recipient_ids")]
        public List<string> RecipientIds { get; set; }

        /// <summary>
        /// Limits to messages for the given tenants
        /// </summary>
        [JsonProperty("tenants")]
        public List<string> Tenants { get; set; }

        /// <summary>
        /// Limits to messages generated with the given trigger data, as a JSON string
        /// </summary>
        [JsonProperty("trigger_data")]
        public string TriggerData { get; set; }

        /// <summary>
        /// Limits to messages generated by the given workflow keys
        /// </summary>
        [JsonProperty("workflows")]
        public List<string> Workflows { get; set; }
    }
}
